# Generated by Django 5.1.5 on 2025-02-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_picture/noprf.webp', null=True, upload_to='profile_picture/'),
        ),
    ]
